### PR TITLE
Client ui update

### PR DESCRIPTION
**Pull request by kldavis4**
The top-level folder icons can be configured via the config file to display the folder name or not (see Client.display_root_folder_names). At some point we can wire this so the admin UI can update this. The folder names will automatically pick up the correct font awesome icon if the match either the id or name of the icon style (music or Music). If it doesn’t match and nothing else is specified, it defaults to a folder icon. A font awesome icon can also be specified for a folder named differently by creating an empty file at the same level as the directory of the format `<prefix>_<foldername>_<fa-class>` where prefix is configurable and is currently `_icon_`, folder name is the name of the folder, and fa-class is the full font awesome class to be applied. Ex. `_icon_Music_fa-home`. A user supplied image can also be used as an icon by naming it `<prefix>_<foldername>.[ext]` where ext is the image extension. Ex. `_icon_Music.jpg`. The custom folder icon functionality applies at both the top-level and sub-folders.

### CODE REVIEW

**Comment by edwinsteele** [comment]
Looking good. I’ve seen it:

* matching fa names for folders at the top level
* text file showing at the top level
* defaulting to a default icon at the top level
* overriding the folder icon at the top level
* using a user-supplied image at the top level
* seeing the house replacing the “root” text

A few thoughts:

* we should resize images (not sure what a reasonable max height and width would be, though)
* it would be good to have the sample content repo (https://github.com/ConnectBox/connectbox-sample-content) demonstrate all of these capabilities. Do you think you could add something in that repo?
* Is the interface stable enough to add some selenium tests?

**Comment by kldavis4** [comment]
I definitely think the image resizing would be a good thing, but I am not sure how best to deal with it. Because the fa icons have different aspect ratios, I think the resizing will have to be intelligent depending on the aspect ratio of the image. I think we should create an issue to tackle it separately.

I have updated the sample content repo with examples of the new functionality. I also just committed a change to this branch to make the name based folder matching case-insensitive.

**Comment by kldavis4** [comment]
Also, I think the interface is stable enough for selenium tests. The only additional major changes I think are the chat and the popular files components. Thanks for the review!

**Comment by kldavis4** [comment]
Thanks again. I'm going to try this: http://stackoverflow.com/a/23675095/290918 and see if it works for the image resizing and then will merge this.

**Pull request merged**
